### ISSUE TITLE
Looking for maintainers?

### ISSUE THREAD

**Issue by jhongturney** [Makeshift/generate-dependabot-glob-action#26]
Hello 👋 

It looks like this excellent action could use a little love, even just the basics like approving dependabot updates.  I use this pretty frequently and would like to see it just kept up-to-date, even if we don't have much time to get to new features.  Are you interested in a helping hand?

**Comment by jhongturney** [comment]
@Makeshift @florianmutter Just a little ping, in case you might like a hand 🙇

**Comment by jhongturney** [comment]
Created a fork at jhongturney/generate-dependabot-glob-action and updated the bits to release a v1.0.0, but otherwise no functional changes.  I can create a PR for this project if wanted, just let me know.

**Comment by Makeshift** [comment]
Hey @jhongturney!

I'm sorry for not replying for so long, and I really appreciate your offer and input. 

I think with my lack of response it's evident I simply don't have time to maintain this, so I think the best course of action is likely what you've done already - creating a fork which will hopefully be easier for both yourself and the wider community to contribute to and maintain.

Based on the traffic on the related [Dependabot issue](https://github.com/dependabot/dependabot-core/issues/2178), it's possible that an action like this won't be needed for much longer, but we'll see :)
