### ISSUE TITLE
Inject comment in generated file

### ISSUE THREAD

**Issue by object88** [Makeshift/generate-dependabot-glob-action#6]
A lot of my org is aware of Dependabot, and it's easily "googleable".  Dependabot file _generation_ is not yet.  It would be really useful to me to allow the generator to inject a (customizable?) header on the generated file that indicates, _Do not modify this file directly; modify dependabot.template.yaml_.  The motivation is that further generations of SRE / DevOps / Engineers / etc. can avoid the mistake of changing the generated file directly, and losing those changes when this action runs at a later time.

I _could_ put such a message in the template file directly, but it feels awkward to put a message there that says "don't change this file, change (the same) file".

In practice, the common case would be that when the `generate-dependable-glob-action` GHA workflow creates a PR, and that PR shows overwritten changes, but it feels like that could be an avoidable frustration for whomever is managing the PR.

**Comment by object88** [comment]
And now I'm confused.  I see _exactly_ what I want in [the source code](https://github.com/Makeshift/generate-dependabot-glob-action/blob/master/src/index.js#L45-L46), but it did not show up in my generated Dependabot file.

**Comment by object88** [comment]
Ah, OK.  The feature is implemented, but the action is still run from [this commit SHA](https://github.com/Makeshift/generate-dependabot-glob-action/blob/d8c935544c57620c0143ab2b57b16680c6cf7cff/src/index.js).  So just waiting for a new release of the action.

Case closed.  :D

**Comment by Makeshift** [comment]
Now finished implementing properly and released - I forgot to build 😁
